"""
Search Engine Module - Google News Search Operations
=====================================================

This module contains Google News search operations.
"""

import asyncio
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Optional, Set
from urllib.parse import quote

import aiohttp
from aiohttp_socks import ProxyConnector

from services.network import ProxyManager, PROXY_STEP_NEWS_SEARCH
from news_scraper.async_utils import run_async
from core import get_standard_logger

# Google News RSS language/region mapping
_LANG_TO_GEO: Dict[str, tuple] = {
    "en": ("US", "US:en"),
    "tr": ("TR", "TR:tr"),
}
_DEFAULT_GEO = ("US", "US:en")

# RSS time filter query operators
_WHEN_TO_OPERATOR: Dict[str, str] = {
    "h": "when:1h",
    "d": "when:1d",
    "w": "when:7d",
    "m": "when:30d",
    "y": "when:1y",
}


class SearchAPIError(Exception):
    """Raised when Google News returns an unexpected error."""


class GoogleNewsSearchEngine:
    """Specialized class for Google News search operations."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.logger = get_standard_logger(__name__)

        # Extract configuration
        network_cfg = self.config.get("network", {})
        web_search_config = self.config.get("web_search", {})
        proxy_config = self.config.get("proxy", {})

        # Network parameters
        self.request_timeout = network_cfg.get("request_timeout_seconds", 30)
        self.max_retry_count = network_cfg.get("max_retry_count", 3)
        self.verify_ssl = bool(network_cfg.get("verify_ssl", True))

        if not self.verify_ssl:
            self.logger.warning(
                "SSL verification disabled for news search; set network.verify_ssl=True for production safety."
            )

        # Web search settings
        self.total_searches = web_search_config.get("total_searches", 3)
        self.search_delay_seconds = web_search_config.get("search_delay_seconds", 2)
        self.max_concurrent_requests = max(
            1, int(web_search_config.get("max_concurrent_requests", 4))
        )

        # Business logic flags
        self.use_company_keywords = self.config.get("use_company_keywords", True)

        # Proxy manager (for the news_search step)
        self.proxy_manager = ProxyManager(proxy_config, step=PROXY_STEP_NEWS_SEARCH)

    def google_news_search_multi(
        self,
        company_name: str,
        company_details: Dict[str, Any],
        max_queries: Optional[int] = None,
        ai_keywords: Optional[List[Dict[str, str]]] = None,
    ) -> List[Dict[str, str]]:
        """Perform a comprehensive Google News search with multiple keywords (async wrapper)."""
        try:
            return run_async(
                self.google_news_search_multi_async(
                    company_name,
                    company_details,
                    max_queries=max_queries,
                    ai_keywords=ai_keywords,
                )
            )
        except RuntimeError as exc:
            self.logger.warning("Async execution failed: %s", exc)
            return []

    async def google_news_search_multi_async(
        self,
        company_name: str,
        company_details: Dict[str, Any],
        max_queries: Optional[int] = None,
        ai_keywords: Optional[List[Dict[str, str]]] = None,
    ) -> List[Dict[str, str]]:
        """Perform comprehensive Google News search with multiple keywords and combine results.

        KISS and YAGNI principles:
        - Broader search scope
        - Multiple source support
        - AI-powered keyword strategy
        - Duplicate prevention and quality control
        - Query count based on keyword count or max_queries parameter

        Arguments:
            company_name: Company name
            company_details: Company details (e.g., symbol, sector, industry)
            max_queries: Maximum query count (determined by user role)
            ai_keywords: Keywords generated by AI [{"term": "...", "pages": 1, "lang": "en"}]
        """
        try:
            queries: List[Dict[str, Any]] = []
            queries_seen: Set[str] = set()

            company_details = company_details or {}
            sector = (company_details.get("sector") or "").strip()
            industry = (company_details.get("industry") or "").strip()

            def add_query(term: str, pages: int = 1, lang: str = "en") -> None:
                if term and term not in queries_seen:
                    queries.append({"term": term, "pages": pages, "lang": lang})
                    queries_seen.add(term)

            # Prefer AI-generated keywords first
            if ai_keywords:
                self.logger.info(
                    "🤖 Using AI-generated keywords: %d items", len(ai_keywords)
                )
                for kw in ai_keywords:
                    term = kw.get("term", "").strip()
                    pages = kw.get("pages", 1)
                    lang = kw.get("lang", "en")
                    if term:
                        try:
                            pages = int(pages)
                        except (ValueError, TypeError):
                            pages = 1
                        add_query(term, pages, lang)

            # Fall back to the existing strategy if no AI keywords are available
            if not queries:
                self.logger.info(
                    "⚠️ No AI keywords available; using the default strategy"
                )

                symbol = company_details.get("symbol", "")
                is_tr = symbol.endswith(".IS")
                def_lang = "tr" if is_tr else "en"
                news_suffix = "haberleri" if is_tr else "news"

                add_query(company_name, pages=1, lang=def_lang)
                add_query(f"{company_name} {news_suffix}", pages=1, lang=def_lang)

                if self.use_company_keywords:
                    context_terms = [term for term in (sector, industry) if term]
                    for context_term in context_terms:
                        add_query(
                            f"{company_name} {context_term}", pages=1, lang=def_lang
                        )

            max_queries_final = (
                max_queries
                if max_queries is not None
                else max(len(queries), self.total_searches)
            )

            aggregated: List[Dict[str, str]] = []
            seen_urls: Set[str] = set()
            seen_titles: Set[str] = set()

            limited_queries = queries[: min(max_queries_final, len(queries))]
            self.logger.info(
                "🔍 Google News search: %d queries planned", len(limited_queries)
            )

            semaphore = asyncio.Semaphore(self.max_concurrent_requests)
            merge_lock = asyncio.Lock()

            async def _fetch_and_merge(
                term: str, lang: str, page: int, delay: float
            ) -> None:
                if delay > 0:
                    await asyncio.sleep(delay)
                async with semaphore:
                    try:
                        self.logger.info(
                            "Searching query '%s' (page %d, lang: %s)...",
                            term,
                            page,
                            lang,
                        )
                        results = await self.fetch_google_news_async(
                            term, lang=lang, page=page
                        )
                    except SearchAPIError as e:
                        self.logger.warning(
                            "Query SearchAPIError '%s' P%d: %s", term, page, e
                        )
                        return
                    except (aiohttp.ClientError, ValueError) as e:
                        self.logger.warning("Query error '%s' P%d: %s", term, page, e)
                        return
                    except (KeyError, AttributeError) as e:
                        self.logger.warning(
                            "Data processing error '%s' P%d: %s", term, page, e
                        )
                        return

                if not results:
                    return

                new_count = 0
                async with merge_lock:
                    for item in results:
                        url = item.get("link", "")
                        title = item.get("title", "").lower().strip()

                        if not url or url in seen_urls:
                            continue
                        if title in seen_titles:
                            continue
                        if len(title) < 10:
                            continue

                        seen_urls.add(url)
                        seen_titles.add(title)
                        aggregated.append(item)
                        new_count += 1

                self.logger.info(
                    "Query '%s' P%d found %d new articles (total: %d)",
                    term,
                    page,
                    new_count,
                    len(aggregated),
                )

            tasks: List[asyncio.Task[None]] = []
            for idx, q_obj in enumerate(limited_queries):
                term = q_obj["term"]
                lang = q_obj["lang"]
                # RSS paging is not supported; only page 1 is requested
                delay = (
                    float(idx * self.search_delay_seconds)
                    if self.search_delay_seconds > 0
                    else 0.0
                )
                tasks.append(
                    asyncio.create_task(_fetch_and_merge(term, lang, 1, delay))
                )

            if tasks:
                await asyncio.gather(*tasks)

            self.logger.info("✅ Total %d unique articles found", len(aggregated))
            return aggregated

        except (aiohttp.ClientError, ValueError) as e:
            self.logger.warning("google_news_search_multi error: %s", e)
            return []
        except (KeyError, AttributeError) as e:
            self.logger.warning("google_news_search_multi data error: %s", e)
            return []

    def fetch_google_news(
        self,
        query: str,
        max_results: Optional[int] = None,
        lang: str = "en",
        page: int = 1,
        time_period: Optional[str] = None,
    ) -> List[Dict[str, str]]:
        """Fetch Google News search results (async wrapper)."""
        try:
            return run_async(
                self.fetch_google_news_async(
                    query,
                    max_results=max_results,
                    lang=lang,
                    page=page,
                    time_period=time_period,
                )
            )
        except RuntimeError as exc:
            self.logger.warning("Async execution failed: %s", exc)
            return []

    async def fetch_google_news_async(
        self,
        query: str,
        max_results: Optional[int] = None,
        lang: str = "en",
        page: int = 1,
        time_period: Optional[str] = None,
    ) -> List[Dict[str, str]]:
        """Fetch Google News search results asynchronously from the RSS feed."""

        # RSS paging is not supported; page > 1 returns an empty list
        if page > 1:
            return []

        # Time filter: append a query operator instead of a URL parameter
        full_query = query
        if time_period and time_period in _WHEN_TO_OPERATOR:
            full_query = f"{query} {_WHEN_TO_OPERATOR[time_period]}"

        # Language/region mapping
        geo_code, ceid = _LANG_TO_GEO.get(lang, _DEFAULT_GEO)

        encoded_query = quote(full_query)
        rss_url = (
            f"https://news.google.com/rss/search"
            f"?q={encoded_query}&hl={lang}&gl={geo_code}&ceid={ceid}"
        )

        headers: Dict[str, str] = {
            "User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
            "Accept": "application/rss+xml, application/xml, text/xml, */*",
        }

        rss_text: Optional[str] = None

        for attempt in range(1, self.max_retry_count + 1):
            proxy = self.proxy_manager.get_proxy()
            proxy_url = None
            connector = None

            if proxy:
                if attempt == 1:
                    self.logger.info(
                        "🔍 [Google News RSS] Arama: '%s' | Proxy: %s", query, proxy
                    )
                proxy = ProxyManager.normalize_proxy_for_aiohttp(proxy)
                if proxy.startswith("socks"):
                    connector = ProxyConnector.from_url(proxy)
                else:
                    proxy_url = proxy
            elif not self.proxy_manager.enabled or not self.proxy_manager.proxies:
                if attempt == 1:
                        self.logger.warning(
                            "⚠️  [Google News RSS] Search: '%s' | proxy disabled", query
                        )
            else:
                self.logger.warning(
                    "⚠️  [Google News RSS] Search: '%s' (attempt %d) | no available proxy",
                    query,
                    attempt,
                )

            try:
                timeout = aiohttp.ClientTimeout(total=self.request_timeout)
                async with aiohttp.ClientSession(
                    timeout=timeout,
                    connector=connector,
                ) as session:
                    async with session.get(
                        rss_url,
                        headers=headers,
                        proxy=proxy_url,
                        ssl=self.verify_ssl,
                    ) as response:
                        if response.status == 429:
                            self.logger.warning(
                                "Google News RSS rate limit (429) - backing off"
                            )
                            if proxy:
                                self.proxy_manager.mark_proxy_failed(proxy)
                            backoff = min(10 * (2**attempt), 60)
                            await asyncio.sleep(backoff)
                            continue

                        if response.status >= 400:
                            raise SearchAPIError(
                                f"Google News RSS HTTP error: {response.status}"
                            )

                        rss_text = await response.text(
                            encoding="utf-8", errors="replace"
                        )

                if proxy:
                    self.proxy_manager.mark_proxy_success(proxy)
                self.logger.info(
                    "Google News RSS succeeded (attempt %d/%d)",
                    attempt,
                    self.max_retry_count,
                )
                break

            except (aiohttp.ClientError, asyncio.TimeoutError) as e:
                error_msg = str(e)
                self.logger.warning(
                    "Google News RSS request failed (%s/%s): %s",
                    attempt,
                    self.max_retry_count,
                    error_msg,
                )

                if proxy:
                    self.proxy_manager.mark_proxy_failed(proxy)

                if attempt == self.max_retry_count:
                    self.logger.error(
                        "Google News RSS giving up after %s attempts: %s",
                        self.max_retry_count,
                        e,
                    )
                    raise SearchAPIError(f"Failed to connect to Google News RSS: {e}")

                backoff = min(attempt * 5, 15)
                await asyncio.sleep(backoff)
        else:
            raise SearchAPIError("Google News RSS fetch failed after retries.")

        if not rss_text:
            return []

        # XML parsing
        news_results: List[Dict[str, str]] = []
        try:
            root = ET.fromstring(rss_text)
        except ET.ParseError as e:
            self.logger.warning("RSS XML parsing error: %s", e)
            return []

        for item in root.findall(".//item"):
            try:
                title = item.findtext("title") or ""
                link = item.findtext("link") or ""
                pub_date = item.findtext("pubDate") or ""
                source_elem = item.find("source")
                source = (
                    source_elem.text.strip()
                    if source_elem is not None and source_elem.text
                    else ""
                )

                # Remove the source name from the title ("Title - Source" → "Title")
                if source and title.endswith(f" - {source}"):
                    title = title[: -(len(source) + 3)].strip()

                if title and link:
                    news_results.append(
                        {
                            "title": title,
                            "link": link,
                            "time": pub_date,
                            "source": source,
                        }
                    )
            except Exception as e:
                self.logger.warning("RSS item parse error: %s", e)
                continue

        if max_results is not None:
            try:
                if not (isinstance(max_results, float) and max_results == float("inf")):
                    max_results_int = int(max_results)
                    if max_results_int > 0:
                        news_results = news_results[:max_results_int]
            except (ValueError, TypeError, OverflowError):
                pass

        return news_results

    def search_company_news(
        self,
        company_name: str,
        ticker: str,
        max_results: Optional[int] = None,
        ai_keywords: Optional[List[Dict[str, str]]] = None,
    ) -> List[Dict[str, str]]:
        """Perform a news search for a company (async wrapper)."""
        try:
            return run_async(
                self.search_company_news_async(
                    company_name,
                    ticker,
                    max_results=max_results,
                    ai_keywords=ai_keywords,
                )
            )
        except RuntimeError as exc:
            self.logger.warning("Async execution failed: %s", exc)
            return []

    async def search_company_news_async(
        self,
        company_name: str,
        ticker: str,
        max_results: Optional[int] = None,
        ai_keywords: Optional[List[Dict[str, str]]] = None,
    ) -> List[Dict[str, str]]:
        """Perform a news search for a company.

        Args:
            company_name: Company name
            ticker: Stock ticker symbol
            max_results: Maximum result count (None = unlimited)
            ai_keywords: AI-generated keywords [{"term": "...", "pages": 1, "lang": "en"}]
        """
        try:
            company_details: Dict[str, Any] = {"symbol": ticker} if ticker else {}
            aggregated_news = await self.google_news_search_multi_async(
                company_name,
                company_details,
                ai_keywords=ai_keywords,
            )

            if not aggregated_news:
                return []

            if max_results is not None and max_results > 0:
                return aggregated_news[:max_results]
            return aggregated_news

        except Exception as e:
            self.logger.error("Company news search error: %s", e)
            return []
